# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jpeg2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(513, 0, 451, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_output1_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output1_5.setObjectName("verticalLayout_output1_5")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_output1_5.addWidget(self.label_9)
        self.out3 = QtWidgets.QLabel(self.layoutWidget)
        self.out3.setObjectName("out3")
        self.verticalLayout_output1_5.addWidget(self.out3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_output1_5)
        self.verticalLayout_output2_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output2_5.setObjectName("verticalLayout_output2_5")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_output2_5.addWidget(self.label_10)
        self.out4 = QtWidgets.QLabel(self.layoutWidget)
        self.out4.setObjectName("out4")
        self.verticalLayout_output2_5.addWidget(self.out4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_output2_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_output1_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output1_2.setObjectName("verticalLayout_output1_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_output1_2.addWidget(self.label_5)
        self.out7 = QtWidgets.QLabel(self.layoutWidget)
        self.out7.setObjectName("out7")
        self.verticalLayout_output1_2.addWidget(self.out7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_output1_2)
        self.verticalLayout_output2_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output2_2.setObjectName("verticalLayout_output2_2")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_output2_2.addWidget(self.label_16)
        self.out8 = QtWidgets.QLabel(self.layoutWidget)
        self.out8.setObjectName("out8")
        self.verticalLayout_output2_2.addWidget(self.out8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_output2_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(60, 0, 451, 551))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_output1_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output1_3.setObjectName("verticalLayout_output1_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_output1_3.addWidget(self.label_7)
        self.out1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.out1.setObjectName("out1")
        self.verticalLayout_output1_3.addWidget(self.out1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_output1_3)
        self.verticalLayout_output2_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output2_3.setObjectName("verticalLayout_output2_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_output2_3.addWidget(self.label_8)
        self.out2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.out2.setObjectName("out2")
        self.verticalLayout_output2_3.addWidget(self.out2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_output2_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_output1_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output1_4.setObjectName("verticalLayout_output1_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_output1_4.addWidget(self.label_3)
        self.out5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.out5.setObjectName("out5")
        self.verticalLayout_output1_4.addWidget(self.out5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_output1_4)
        self.verticalLayout_output2_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_output2_4.setObjectName("verticalLayout_output2_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_output2_4.addWidget(self.label_4)
        self.out6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.out6.setObjectName("out6")
        self.verticalLayout_output2_4.addWidget(self.out6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_output2_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Browse Jpeg"))
        self.label_9.setText(_translate("MainWindow", "Scan 3"))
        self.out3.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Scan 4"))
        self.out4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Scan 7"))
        self.out7.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.out8.setText(_translate("MainWindow", "Scan 8"))
        self.label_7.setText(_translate("MainWindow", "Scan 1"))
        self.out1.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Scan 2 "))
        self.out2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Scan 5"))
        self.out5.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Scan 6"))
        self.out6.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

